[build]
builder = "nixpacks"
buildCommand = "./gradlew :appServer:shadowJar"

[deploy]
startCommand = "java $JAVA_OPTS -jar appServer/build/libs/appServer-all.jar"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
