package com.mediasage.data.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters
import com.mediasage.data.local.dao.DailyReflectionDao
import com.mediasage.data.local.dao.DayAssignmentDao
import com.mediasage.data.local.dao.EncouragementDao
import com.mediasage.data.local.dao.FigureDao
import com.mediasage.data.local.dao.HeadlineDao
import com.mediasage.data.local.dao.MatchDao
import com.mediasage.data.local.dao.PinnedFigureDao
import com.mediasage.data.local.dao.QuoteDao
import com.mediasage.data.local.dao.SyncMetaDao
import com.mediasage.data.local.entity.DailyReflectionEntity
import com.mediasage.data.local.entity.DayAssignmentEntity
import com.mediasage.data.local.entity.EncouragementEntity
import com.mediasage.data.local.entity.FigureEntity
import com.mediasage.data.local.entity.HeadlineEntity
import com.mediasage.data.local.entity.MatchEntity
import com.mediasage.data.local.entity.PinnedFigureEntity
import com.mediasage.data.local.entity.QuoteEntity
import com.mediasage.data.local.entity.SyncMetaEntity

@Database(
    entities = [
        FigureEntity::class,
        QuoteEntity::class,
        HeadlineEntity::class,
        MatchEntity::class,
        EncouragementEntity::class,
        SyncMetaEntity::class,
        DailyReflectionEntity::class,
        PinnedFigureEntity::class,
        DayAssignmentEntity::class,
    ],
    version = 17,
    exportSchema = true
)
@TypeConverters(Converters::class)
@ConstructedBy(MediaSageDatabaseConstructor::class)
abstract class MediaSageDatabase : RoomDatabase() {
    abstract fun figureDao(): FigureDao
    abstract fun quoteDao(): QuoteDao
    abstract fun headlineDao(): HeadlineDao
    abstract fun matchDao(): MatchDao
    abstract fun encouragementDao(): EncouragementDao
    abstract fun syncMetaDao(): SyncMetaDao
    abstract fun dailyReflectionDao(): DailyReflectionDao
    abstract fun pinnedFigureDao(): PinnedFigureDao
    abstract fun dayAssignmentDao(): DayAssignmentDao
}

// KMP Room requires this — the implementation is generated by KSP at compile time
@Suppress("NO_ACTUAL_FOR_EXPECT", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object MediaSageDatabaseConstructor : RoomDatabaseConstructor<MediaSageDatabase> {
    override fun initialize(): MediaSageDatabase
}
