package com.mediasage.data.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters
import com.mediasage.data.local.dao.EncouragementDao
import com.mediasage.data.local.dao.FigureDao
import com.mediasage.data.local.dao.HeadlineDao
import com.mediasage.data.local.dao.MatchDao
import com.mediasage.data.local.dao.QuoteDao
import com.mediasage.data.local.entity.EncouragementEntity
import com.mediasage.data.local.entity.FigureEntity
import com.mediasage.data.local.entity.HeadlineEntity
import com.mediasage.data.local.entity.MatchEntity
import com.mediasage.data.local.entity.QuoteEntity

@Database(
    entities = [
        FigureEntity::class,
        QuoteEntity::class,
        HeadlineEntity::class,
        MatchEntity::class,
        EncouragementEntity::class
    ],
    version = 5,
    exportSchema = true
)
@TypeConverters(Converters::class)
@ConstructedBy(MediaSageDatabaseConstructor::class)
abstract class MediaSageDatabase : RoomDatabase() {
    abstract fun figureDao(): FigureDao
    abstract fun quoteDao(): QuoteDao
    abstract fun headlineDao(): HeadlineDao
    abstract fun matchDao(): MatchDao
    abstract fun encouragementDao(): EncouragementDao
}

// KMP Room requires this — the implementation is generated by KSP at compile time
@Suppress("NO_ACTUAL_FOR_EXPECT", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object MediaSageDatabaseConstructor : RoomDatabaseConstructor<MediaSageDatabase> {
    override fun initialize(): MediaSageDatabase
}
