default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    key_params = if ENV['APP_STORE_CONNECT_KEY_CONTENT']
      { key_content: ENV['APP_STORE_CONNECT_KEY_CONTENT'] }
    else
      { key_filepath: "fastlane/AuthKey_8WVFL729XV.p8" }
    end
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'] || "8WVFL729XV",
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'] || "4b15de7b-0249-4d99-b657-e2d2dda326f2",
      **key_params
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: true
    )

    increment_build_number(
      build_number: ENV['BUILD_NUMBER'] || Time.now.to_i.to_s,
      xcodeproj: "iosApp/iosApp.xcodeproj"
    )

    build_app(
      scheme: "iosApp",
      project: "iosApp/iosApp.xcodeproj",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
