package com.mediasage.pipeline.core

/**
 * Token usage and cost captured from the Claude Code `result` event at the end of a worker run.
 *
 * All fields map directly to the stream-json `result` event:
 *   { "type": "result", "total_cost_usd": ..., "duration_ms": ..., "num_turns": ...,
 *     "usage": { "input_tokens": ..., "output_tokens": ...,
 *                "cache_read_input_tokens": ..., "cache_creation_input_tokens": ... } }
 *
 * Stored as nullable columns in the `jobs` table so that rows created before MS-210
 * and any run where log fetch fails degrade gracefully rather than failing the job.
 *
 * @property inputTokens Number of tokens in the prompt sent to the model.
 * @property outputTokens Number of tokens generated by the model.
 * @property cacheReadTokens Number of prompt tokens served from the prompt cache.
 * @property cacheCreationTokens Number of prompt tokens written into the prompt cache.
 * @property totalCostUsd Total API cost for the run in US dollars.
 * @property durationMs Wall-clock duration of the worker run in milliseconds.
 * @property numTurns Number of agentic turns (tool-call/response cycles) completed.
 */
data class WorkerMetrics(
    val inputTokens: Int,
    val outputTokens: Int,
    val cacheReadTokens: Int,
    val cacheCreationTokens: Int,
    val totalCostUsd: Double,
    val durationMs: Long,
    val numTurns: Int
)
